use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

// ── Shared domain types for proxy-config & proxy-store ──

/// Wrapper type for session identifiers.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(pub String);

impl SessionId {
    pub fn new(id: String) -> Self { Self(id) }
    pub fn as_str(&self) -> &str { &self.0 }
}

impl std::fmt::Display for SessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

impl From<String> for SessionId {
    fn from(s: String) -> Self { Self(s) }
}

/// Wrapper type for task identifiers (ULID-based).
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaskId(pub String);

impl TaskId {
    pub fn new(id: String) -> Self { Self(id) }
    pub fn generate() -> Self { Self(ulid::Ulid::new().to_string()) }
    pub fn as_str(&self) -> &str { &self.0 }
}

impl std::fmt::Display for TaskId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Token usage for a single task.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TaskUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
}

/// Micro-USD rates per 1M tokens.
///
/// All rates are stored as integers (micro-USD) to avoid floating-point drift.
/// Example: $3/1M tokens → 3_000_000 micro-USD/1M tokens.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PriceRates {
    pub input_microusd: i64,
    pub output_microusd: i64,
    pub cache_write_microusd: i64,
    pub cache_read_microusd: i64,
}

impl Default for PriceRates {
    fn default() -> Self {
        Self {
            input_microusd: 0,
            output_microusd: 0,
            cache_write_microusd: 0,
            cache_read_microusd: 0,
        }
    }
}

/// A snapshot of billing parameters at the time a task is created.
///
/// Frozen into the task row so historical costs never change when
/// the global pricing config is updated.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BillingSnapshot {
    pub pricing_model_id: String,
    pub provider: String,
    pub resolved_model: String,
    pub rates: PriceRates,
    pub currency: String,
}

/// Normalized SSE response body.
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct NormalizedResponse {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub thinking: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub text: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ToolCallRecord>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_results: Vec<ToolResultRecord>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolCallRecord {
    pub id: String,
    pub name: String,
    pub input: serde_json::Value,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolResultRecord {
    pub tool_use_id: String,
    pub content: String,
}

/// Summary of a single task (generated by proxy-core summary analyzer).
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct TaskSummary {
    pub user_request: Option<String>,
    pub assistant_result: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub touched_files: Vec<String>,
}

/// Time range filter for queries.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TimeRange {
    pub from: Option<DateTime<Utc>>,
    pub to: Option<DateTime<Utc>>,
}

/// Status of a proxied task.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    Recording,
    Completed,
    Failed,
    Cancelled,
    Interrupted,
}

impl TaskStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Recording => "recording",
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
            Self::Interrupted => "interrupted",
        }
    }
}

impl Default for TaskStatus {
    fn default() -> Self { Self::Recording }
}

/// Client type identifier.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[repr(i64)]
pub enum ClientType {
    ClaudeCode = 0,
    Codex = 1,
}

impl ClientType {
    pub fn to_i64(self) -> i64 {
        self as i64
    }

    pub fn from_i64(v: i64) -> Self {
        match v {
            1 => Self::Codex,
            _ => Self::ClaudeCode,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::ClaudeCode => "claudecode",
            Self::Codex => "codex",
        }
    }
}

impl Default for ClientType {
    fn default() -> Self { Self::ClaudeCode }
}

impl TryFrom<&str> for ClientType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "codex" => Ok(Self::Codex),
            "claudecode" => Ok(Self::ClaudeCode),
            _ => Err(format!("unknown client_type: {}", s)),
        }
    }
}

// ── Existing types (kept for proxy-server backward compat) ──

/// Trait for items that have a string id (used by RingBuffer::get_by_id).
pub trait HasId {
    fn id(&self) -> &str;
}

impl HasId for ProxiedRequest {
    fn id(&self) -> &str {
        &self.id
    }
}

impl HasId for HookEvent {
    fn id(&self) -> &str {
        &self.id
    }
}

fn short_id() -> String {
    Uuid::new_v4().to_string()[..12].to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ProxiedRequest {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    // Request
    pub method: String,
    pub path: String,
    pub request_headers: HashMap<String, String>,
    pub request_body: Option<String>,
    pub model: Option<String>,
    pub provider: Option<String>,   // routing decision writes the provider name here
    pub is_streaming: bool,
    pub max_tokens: Option<u32>,
    // Response
    pub status_code: Option<u16>,
    pub response_headers: HashMap<String, String>,
    pub response_body: Option<String>,
    pub message_id: Option<String>,
    pub stop_reason: Option<String>,
    pub input_tokens: Option<u32>,
    pub output_tokens: Option<u32>,
    pub cache_creation_input_tokens: Option<u32>,
    pub cache_read_input_tokens: Option<u32>,
    // Streaming
    pub sse_events: Vec<SseEvent>,
    pub content_text: Option<String>,
    // Timing
    pub duration_ms: Option<u64>,
    pub time_to_first_token_ms: Option<u64>,
    // Session tracking
    pub session_id: Option<String>,
    // Request type: "anthropic" or "mcp"
    pub request_type: String,
    // Error
    pub error: Option<String>,
    // Derived: number of messages in request body (populated in list queries, not stored)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub messages_count: Option<u32>,
    // Stored: compact summary of last message for fast list display, no body needed
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_msg_summary: Option<String>,
    /// Computed cost in USD (set after response, used to increment session total).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<f64>,
}

impl ProxiedRequest {
    pub fn new(method: &str, path: &str) -> Self {
        Self {
            id: short_id(),
            timestamp: Utc::now(),
            method: method.to_string(),
            path: path.to_string(),
            request_type: "anthropic".to_string(),
            ..Default::default()
        }
    }

    pub fn new_mcp(method: &str, path: &str) -> Self {
        Self {
            id: short_id(),
            timestamp: Utc::now(),
            method: method.to_string(),
            path: path.to_string(),
            request_type: "mcp".to_string(),
            ..Default::default()
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SseEvent {
    pub event_type: Option<String>,
    pub data: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookEvent {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub hook_event_name: String,
    pub session_id: String,
    pub cwd: String,
    pub permission_mode: String,
    pub transcript_path: String,
    pub hook_input: serde_json::Value,
    pub environment_variables: HashMap<String, String>,
    pub exit_code: i32,
    pub stdout: String,
    pub stderr: String,
}

impl HookEvent {
    pub fn new(hook_event_name: String, session_id: String, cwd: String) -> Self {
        Self {
            id: short_id(),
            timestamp: Utc::now(),
            hook_event_name,
            session_id,
            cwd,
            permission_mode: String::new(),
            transcript_path: String::new(),
            hook_input: serde_json::Value::Null,
            environment_variables: HashMap::new(),
            exit_code: 0,
            stdout: String::new(),
            stderr: String::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct McpRequest {
    pub jsonrpc: String,
    pub method: String,
    pub params: Option<serde_json::Value>,
    pub id: Option<serde_json::Value>,
}

// ── Session model ──

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SessionStatus {
    Recording,
    Stopped,
    /// Requests have been cleaned up, only the tombstone + aggregates remain.
    Archived,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Session {
    pub id: String,
    pub label: Option<String>,
    pub started_at: DateTime<Utc>,
    pub ended_at: Option<DateTime<Utc>>,
    /// IDs of requests currently alive in DB.
    pub request_ids: Vec<String>,
    pub status: SessionStatus,
    /// Aggregated input tokens (includes deleted requests, updated on cleanup).
    pub total_input_tokens: u64,
    /// Aggregated output tokens (includes deleted requests, updated on cleanup).
    pub total_output_tokens: u64,
    /// Total historical request count (includes deleted requests).
    pub request_count: u64,
    /// Accumulated cost in USD (updated per-request, survives cleanup).
    #[serde(default)]
    pub total_cost: f64,
}

impl Session {
    pub fn new(label: Option<String>) -> Self {
        let label = label.filter(|l| !l.is_empty()).unwrap_or_else(|| {
            Utc::now().format("Recording %Y-%m-%d %H:%M").to_string()
        });
        Self {
            id: short_id(),
            label: Some(label),
            started_at: Utc::now(),
            ended_at: None,
            request_ids: Vec::new(),
            status: SessionStatus::Recording,
            total_input_tokens: 0,
            total_output_tokens: 0,
            request_count: 0,
            total_cost: 0.0,
        }
    }

    pub fn stop(&mut self) {
        self.ended_at = Some(Utc::now());
        self.status = SessionStatus::Stopped;
    }
}

// ── Provider info (for frontend) ──

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderInfo {
    pub name: String,
    pub url: String,
    pub has_token: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proxy: Option<String>,
}

// ── Upstream info (for frontend) ──

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TierRuleInfo {
    pub keywords: Vec<String>,
    pub provider: String,
    pub model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpstreamInfo {
    pub name: String,
    pub active: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub high: Option<TierRuleInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mid: Option<TierRuleInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub low: Option<TierRuleInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<TierRuleInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
}

// ── WebSocket message envelope ──

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum WsMessage {
    NewRequest(ProxiedRequest),
    SseEvent { request_id: String, event: SseEvent },
    RequestUpdated(ProxiedRequest),
    NewHook(HookEvent),
    NewMcp(ProxiedRequest),
    Cleared,
    McpCleared,
    McpConfigChanged { destination_url: Option<String> },
    UpstreamChanged {
        active_upstream: String,
        upstreams: Vec<UpstreamInfo>,
        providers: Vec<ProviderInfo>,
        active_effort: String,
        model_pricing: Vec<crate::config::ModelPricing>,
    },
    History { requests: Vec<ProxiedRequest> },
    HookHistory { events: Vec<HookEvent> },
    McpHistory { requests: Vec<ProxiedRequest> },
    SessionStarted(Session),
    SessionStopped(Session),
    SessionUpdated { request_id: String },
    TeeStatusChanged { enabled: bool },
    /// Sent when the server-side broadcast buffer overflowed for this client
    /// (messages were dropped). The client should re-fetch state via REST
    /// (GET /api/requests etc.) to resynchronize instead of trusting the stream.
    Resync,
}

// ── Cost aggregation data structures ──

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelCost {
    pub model: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderCost {
    pub provider: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionCost {
    pub session_id: String,
    pub session_label: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
    pub request_count: u64,
    pub first_request: String,
    pub last_request: String,
    pub models: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailyCost {
    /// Date string in YYYY-MM-DD format
    pub date: String,
    pub model: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CostData {
    pub from: String,
    pub to: String,
    pub by_model: Vec<ModelCost>,
    pub by_provider: Vec<ProviderCost>,
    pub by_session: Vec<SessionCost>,
    pub by_day: Vec<DailyCost>,
}
